name: Test
on:
  - push
  - pull_request

jobs:
  test:
    name: Run tests
    runs-on: 'ubuntu-20.04'
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"
        process-version:
          - "3"
          - "4"
          - "5"
          - "6"
          - "7"
        exclude:
          - php-version: 7.2
            process-version: 6
          - php-version: 7.3
            process-version: 6
          - php-version: 7.4
            process-version: 7
          - php-version: 7.2
            process-version: 7
    steps:
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set env
        run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
    
      - run: echo $GITHUB_SHA_SHORT

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Update composer
        run: composer --verbose self-update

      - name: Dump composer verson
        run: composer --version

      - name: Validate composer.json
        run: composer --verbose validate

      - name: Install dependencies
        run: "composer require symfony/process:^${{ matrix.process-version }}"

      - name: Run tests
        run: composer test

      - name: Coveralls
        if: matrix.php-version == 7.4
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_PARALLEL: true
        run: |
          php vendor/bin/php-coveralls -v

            
  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Close parallel build
        uses: coverallsapp/github-action@v1
        with:
          parallel-finished: true
